using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Launcher : MonoBehaviour
{
    [SerializeField,Header("’e‚ÌƒvƒŒƒnƒu")] private GameObject bulletPrefab;
    [SerializeField,Header("’e‚Ì‘¬“x")] private float bulletSpeed;
    [SerializeField,Header("Å‰‚Ì’e‚Ì”")] private int numberOfBullets;
    [SerializeField,Header("Å‰‚Ì•úËó‚ÌŠp“x")] private float spreadAngle;
    [SerializeField,Header("”­ËŠÔŠu")] private float bulletSpacing;
    [SerializeField,Header("ˆê‰ñ‚Ì’e‚Ì‘‰Á—Ê")] private int bulletAmount;
    [SerializeField,Header("’e‚ğ‘‚â‚·ŠÔ")] private float createBullet;
    [SerializeField,Header("Šp“x‚ğ‘‚â‚·ŠÔ")] private float timeAngle;
    [SerializeField,Header("‘‰ÁŠp“x")] private float yimespreadAngle;
    [SerializeField,Header("Å‘å’e”")]private int MaxBullet;

    private float BulletsTime;//’eŒo‰ßŠÔ
    private float elaTime;//Šp“xŒo‰ßŠÔ
    private int curBullet;//Œ»İ‚Ì’e
    private float curAngle;//Œ»İ‚ÌŠp“x

     void Start()
    {
        curBullet = numberOfBullets;
        curAngle = spreadAngle;
    }

    void Update()
    {
        BulletsTime += Time.deltaTime;
        elaTime += Time.deltaTime;
        if(curBullet < MaxBullet && BulletsTime >= createBullet)
        {
            curBullet += bulletAmount;
            curAngle += yimespreadAngle;
            BulletsTime = 0.0f;
        }
        if(elaTime >= timeAngle)
        {
            Debug.Log("a");
            curAngle += yimespreadAngle;
            elaTime = 0.0f;
        }
        ShootNWayBullets(curBullet,curAngle);
    }

    private void ShootNWayBullets(int curBullet, float curAngle)
    {
        float angleStep = curAngle / (curBullet - 1);
        float initialAngle = transform.eulerAngles.z - (curAngle / 2);
        bulletSpacing += Time.deltaTime;
        if (bulletSpacing > 2.0f)
        {
            for (int i = 0; i < curBullet; i++)
            {
                // ’e‚ğ¶¬‚µ‚ÄA‰ŠúˆÊ’u‚ğİ’è
                GameObject bullet = Instantiate(bulletPrefab, transform.position, Quaternion.identity);
                Rigidbody2D rb = bullet.GetComponent<Rigidbody2D>();

                float bulletAngle = initialAngle + (i * angleStep);

                // ’e‚ÌŒü‚«‚ğƒJƒXƒ^ƒ}ƒCƒY‚·‚é‚½‚ß‚ÉA’e‚ÌŠp“x‚ğ•ÏX
                bullet.transform.rotation = Quaternion.Euler(0, 0, bulletAngle);

                Vector2 bulletDirection = Quaternion.Euler(0, 0, bulletAngle) * Vector2.up;
                rb.velocity = bulletDirection * bulletSpeed;
            }
            bulletSpacing = 0.0f;
        }
            
    }
}
